title: Making Study Populations Visible through Knowledge Graphs
description: A website to navigate resources open-sourced via the associated ISWC 2019 paper, "Making Study Populations Visible through Knowledge Graphs"
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky
